server {
    listen 80;

    location /api/pedidos {
        proxy_pass http://servicio-gestion-pedido:8080; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/inventario { deny all; return 403; }
    location /api/contabilidad { deny all; return 403; }
}