apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grupo5-prod

resources:
  - namespace.yaml
  - ../../base

# Tags que publica GitHub Actions en cada push a main
images:
  - name: ghcr.io/theshac/proyecto-insumos-m-dicos/servicio-gestion-pedido
    newTag: prod-latest
  - name: ghcr.io/theshac/proyecto-insumos-m-dicos/servicio-inventario
    newTag: prod-latest
  - name: ghcr.io/theshac/proyecto-insumos-m-dicos/servicio-contabilidad
    newTag: prod-latest
  - name: ghcr.io/theshac/proyecto-insumos-m-dicos/frontend
    newTag: prod-latest
  - name: ghcr.io/theshac/proyecto-insumos-m-dicos/api-gateway
    newTag: prod-latest

# En producción se entra por prod.grupo5.uta.cl
patches:
  - target:
      kind: Ingress
      name: insumos-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prod.grupo5.uta.cl
