apiVersion: apps/v1
kind: Deployment

metadata:
  name: servicio-gestion-pedido

spec:
  replicas: 1

  selector:
    matchLabels:
      app: servicio-gestion-pedido

  template:
    metadata:
      labels:
        app: servicio-gestion-pedido

    spec:
      containers:
        - name: servicio-gestion-pedido

          image: servicio-gestion-pedido:local
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 3001

          envFrom:
            - configMapRef:
                name: config-pedido

            - secretRef:
                name: secret-pedido

---
apiVersion: v1
kind: Service

metadata:
  name: servicio-gestion-pedido

spec:
  selector:
    app: servicio-gestion-pedido

  ports:
    - name: http
      port: 3001
      targetPort: http

  type: ClusterIP