apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pedidos-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-pedidos

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: postgres-pedidos

  template:
    metadata:
      labels:
        app: postgres-pedidos

    spec:
      containers:
        - name: postgres

          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgres
              containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: pedidos_db

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pedidos-pvc

---
apiVersion: v1
kind: Service

metadata:
  name: postgres-pedidos

spec:
  selector:
    app: postgres-pedidos

  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

  type: ClusterIP