apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grupo5-qa

resources:
  - namespace.yaml
  - ../../base

# Las imágenes :qa las publica GitHub Actions en cada push a develop
images:
  - name: ghcr.io/theshac/servicio-gestion-pedido
    newTag: qa
  - name: ghcr.io/theshac/servicio-inventario
    newTag: qa
  - name: ghcr.io/theshac/servicio-contabilidad
    newTag: qa
  - name: ghcr.io/theshac/frontend
    newTag: qa
  - name: ghcr.io/theshac/api-gateway
    newTag: qa
